name: My Docker CI-CD

on:
  push:
    branches: [ "main" ] # Neenga main branch-la push panna idhu run aagum

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-nginx-app .

      - name: Run Tests
        run: echo "Testing done!"
